### PR TITLE
When exporting Kolasu enum values to LionWeb use Enumeration Literals

### LINKED ISSUE #316: exportModelToLionWeb and enum literals
`JsonSerialization` (and probably other parts of Lionweb) expects enum properties to have values that are instances of `EnumLiteral`, however `exportModelToLionWeb` does not export enums to Lionweb enums, causing serialization of an exported Kolasu node with enum attributes to fail with a class cast exception.

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #316

### CODE REVIEW

File: lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt [hunk 1]
```diff
@@ -416,4 +431,66 @@ class LionWebModelConverterTest {
...
+        val n1 = NodeWithEnum("n1", AnEnum.BAR)
+        val n2 = NodeWithEnum("n2", AnEnum.FOO)
+        val n3 = NodeWithEnum("n3", AnEnum.ZUM)
+        val n4 = NodeWithEnum("n4", null)
+        n1.source = SyntheticSource("someSource")
+        n2.source = SyntheticSource("someSource")
+        n3.source = SyntheticSource("someSource")
+        n4.source = SyntheticSource("someSource")
+
+        // if we store b2, child of a1, we expect the parent to be set
```
Comment (ftomassetti) [inline lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt:478]: I should remove this comment

File: lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt [hunk 2]
```diff
@@ -416,4 +431,66 @@ class LionWebModelConverterTest {
...
```
Comment (ftomassetti) [inline lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt:446]: I should remove this comment

File: lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt [hunk 3]
```diff
@@ -272,6 +273,17 @@ class LionWebLanguageConverter {
             val newEnumeration = Enumeration(lionwebLanguage, kClass.simpleName)
             newEnumeration.id = (lionwebLanguage.id ?: "unknown_language") + "_" + newEnumeration.name
             newEnumeration.key = newEnumeration.name
+
+            val entries = kClass.java.enumConstants
+            entries.forEach { entry ->
+                newEnumeration.addLiteral(
+                    EnumerationLiteral(newEnumeration, entry.name).apply {
+                        setID(newEnumeration.id + "-" + entry.name)
+                        setKey(id)
```
Comment (ftomassetti) [inline lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt:282]: They key should be unique within the language, so it could make sense not to include the language name in it.
Also, we should remove invalid characters, if present

File: lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt (hunk 2 above)
Comment (ftomassetti) [reply lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt]: Fixed

File: lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt (hunk 1 above)
Comment (ftomassetti) [reply lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt]: Fixed

**Review by alessiostalla — APPROVED** [review]

**Comment by ftomassetti** [comment]
Thank you Alessio!
