### PR TITLE
Fix serialization of Serializable

### LINKED ISSUE #187: EMF test failing because Pair is no longer Serializable
Probably the EMF export removes all instances of `Serializable` but one of our tests expected it to be there.

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #187

### CODE REVIEW

File: emf/src/test/kotlin/com/strumenta/kolasu/emf/KolasuMetamodelTest.kt [hunk 1]
```diff
@@ -40,7 +40,6 @@ class KolasuMetamodelTest {
             "java.io", "https://strumenta.com/javaio", "javaio",
             resource
         )
-        javaIOMetamodelBuilder.provideClass(java.io.Serializable::class)
         javaIOMetamodelBuilder.generate()
```
Comment (alessiostalla) [inline emf/src/test/kotlin/com/strumenta/kolasu/emf/KolasuMetamodelTest.kt:43]: Does it still make sense to include a package for java.io that doesn't contain any classes in the StarLasu metamodel?

Comment (ftomassetti) [reply emf/src/test/kotlin/com/strumenta/kolasu/emf/KolasuMetamodelTest.kt:43]: You are right, we should remove it
