### PR TITLE
JSON generator: use nodeType

### LINKED ISSUE #235: JSON generator: use nodeType
Currently, it uses the Java class name but that doesn't work for wrapper/dynamic nodes.

### PR DESCRIPTION
**Pull request by alessiostalla**
Fixes #235

### CODE REVIEW

File: core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt [hunk 1]
```diff
@@ -187,8 +187,9 @@ class JsonGenerator {
         withDestinationIds: IdentityHashMap<Node, String>? = null
     ):
         JsonElement {
+        val nodeType = node.nodeType
         val jsonObject = jsonObject(
-            JSON_TYPE_KEY to if (shortClassNames) node.javaClass.simpleName else node.javaClass.canonicalName,
+            JSON_TYPE_KEY to if (shortClassNames) nodeType.substring(nodeType.indexOf('.') + 1) else nodeType,
```
Comment (ftomassetti) [inline core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt:192]: I think you want to find the last index of '.'. Alternatively I would use `nodeType.split('.').last()`

Comment (alessiostalla) [reply core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt]: Right, good catch!
